--movies
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (1, 'movie', 'Inception', '/Movies/1.png', 'A thief who steals corporate secrets through the use of dream-sharing technology.', 'Christopher Nolan', 2010, '148 min', '8.8/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (2, 'movie', 'Interstellar', '/Movies/2.png', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'Christopher Nolan', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (3, 'movie', 'The Dark Knight', '/Movies/3.png', 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.', 'Christopher Nolan', 2008, '152 min', '9.0/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (4, 'movie', 'The Dark Knight Rises', '/Movies/4.png', 'Eight years after the Joker''s reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City.', 'Christopher Nolan', 2012, '164 min', '8.4/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (5, 'movie', 'Dunkirk', '/Movies/5.png', 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.', 'Christopher Nolan', 2017, '106 min', '7.9/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (6, 'movie', 'Tenet', '/Movies/6.png', 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.', 'Christopher Nolan', 2020, '150 min', '7.4/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (7, 'movie', 'Memento', '/Movies/7.png', 'A man with short-term memory loss attempts to track down his wife''s murderer.', 'Christopher Nolan', 2000, '113 min', '8.4/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (8, 'movie', 'The Prestige', '/Movies/8.png', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.', 'Christopher Nolan', 2006, '130 min', '8.5/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (9, 'movie', 'Insomnia', '/Movies/9.png', 'Two detectives are dispatched to a northern town where the sun doesn''t set to investigate the methodical murder of a local teen.', 'Christopher Nolan', 2002, '118 min', '7.2/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (10, 'movie', 'Following', '/Movies/10.png', 'A young writer who follows strangers for material meets a thief who takes him under his wing.', 'Christopher Nolan', 1998, '69 min', '7.5/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (11, 'movie', 'Inception', '/Movies/1.png', 'A thief who steals corporate secrets through the use of dream-sharing technology.', 'Christopher Nolan', 2010, '148 min', '8.8/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (12, 'movie', 'Interstellar', '/Movies/2.png', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'Christopher Nolan', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');

-- Series
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (13, 'series', 'Breaking Bad', '/Series/1.png', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family''s future.', 'Vince Gilligan', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (14, 'series', 'Game of Thrones', '/Series/2.png', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', 'David Benioff, D.B. Weiss', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (15, 'series', 'Stranger Things', '/Series/3.png', 'When a young fkadsfasd asdf asdf sadf asdf ', 'The Duffer Brothers', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (16, 'series', 'The Crown', '/Series/4.png', 'Follows the political rivalries and romance of Queen Elizabeth II''s reign and the events that shaped the second half of the 20th century.', 'Peter Morgan', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (17, 'series', 'The Mandalorian', '/Series/5.png', 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.', 'Jon Favreau', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (18, 'series', 'The Witcher', '/Series/6.png', 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', 'Lauren Schmidt', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (19, 'series', 'Black Mirror', '/Series/7.png', 'An anthology series exploring a twisted, high-tech multiverse where humanity''s greatest innovations and darkest instincts collide.', 'Charlie Brooker', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (20, 'series', 'The Umbrella Academy', '/Series/8.png', 'A family of former child heroes, now grown apart, must reunite to continue to protect the world.', 'Steve Blackman', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (21, 'series', 'The Queen''s Gambit', '/Series/9.png', 'Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.', 'Scott Frank', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (22, 'series', 'Money Heist', '/Series/10.png', 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.', 'Álex Pina', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (23, 'series', 'Breaking Bad', '/Series/1.png', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family''s future.', 'Vince Gilligan', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');
INSERT INTO mediaElements (id, type, title, poster, description, director, year, duration, rating, trailerID) VALUES (24, 'series', 'Game of Thrones', '/Series/2.png', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', 'David Benioff, D.B. Weiss', 2014, '169 min', '8.6/10', 'KPLWWIOCOOQ');